### ISSUE TITLE
Change of smeltingRecipe in 7.2 cause all smelting recipe implemented manully in 7.1 to break

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/SpongeAPI#1971]
Smelting recipe in spongeAPI 7.1 does not implement `CatalogType`

But change introduced in https://github.com/SpongePowered/SpongeAPI/commit/8c4031f2a846291fc5d7139aeaab13d7c909a914 changes it to implement `CatalogType` without proper default methods.

Thus, all manually implemented smelting recipe in 7.1 will not be register-able in 7.2 due to lacks of CatalogType methods and result in startup crash

**Comment by Cybermaxke** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/40492ed4e9611c8a90088679ae1680a398893134
